version: '3.8'

services:
  mobidic-spring:
    image: pni2399/mobidic-spring:1.0
    ports:
      - "8080:8080"
    networks:
      - mobidic-net
    container_name: mobidic-spring
    restart: unless-stopped
    depends_on:
      - mobidic-mysql
      - mobidic-redis

  mobidic-nginx:
    image: nginx:latest
    container_name: mobidic-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
    depends_on:
      - mobidic-spring
    networks:
      - mobidic-net

  mobidic-certbot:
    image: certbot/certbot
    container_name: mobidic-certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done;'"
    networks:
      - mobidic-net

  mobidic-mysql:
    image: mysql:8.0
    container_name: mobidic-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    networks:
      - mobidic-net
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mobidic-mysql-data:/var/lib/mysql
      - ./mobidic_mysql:/docker-entrypoint-initdb.d

  mobidic-redis:
    image: redis:7-alpine
    container_name: mobidic-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - mobidic-net
    volumes:
      - mobidic-redis-data:/data

  mobidic-flask:
    image: pni2399/mobidic-flask:1.0
    container_name: mobidic-flask
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - mobidic-net

networks:
  mobidic-net:
    external: true

volumes:
  mobidic-mysql-data:
  mobidic-redis-data:
  certbot-etc:
  certbot-var:
