GET http://127.0.0.1:8080/api/rate/w?wId=85105359-f8c6-4ad5-8322-b660aefd74da
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhMWYxMDhjNS1mMjY2LTQxYWEtOTJlNC1iODVhNDM2NmU1MDEiLCJpYXQiOjE3NDQxNzY4MzMsImV4cCI6MTc0NDI2MzIzM30.cEXUPYVXpMEZJ4Iiwd6RMTAtwYpd8RdlKLYihU6XVzO8WjZZPh_jLH9sWBrRKyAOMc6iolXRNh813y2ur2OaXg

{
}
