GET http://127.0.0.1:8080/api/vocab/all?uId=a1f108c5-f266-41aa-92e4-b85a4366e501
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhMWYxMDhjNS1mMjY2LTQxYWEtOTJlNC1iODVhNDM2NmU1MDEiLCJpYXQiOjE3NDQxNzY4MzMsImV4cCI6MTc0NDI2MzIzM30.cEXUPYVXpMEZJ4Iiwd6RMTAtwYpd8RdlKLYihU6XVzO8WjZZPh_jLH9sWBrRKyAOMc6iolXRNh813y2ur2OaXg

{
}
