POST http://127.0.0.1:8080/api/vocab/a1f108c5-f266-41aa-92e4-b85a4366e501
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhMWYxMDhjNS1mMjY2LTQxYWEtOTJlNC1iODVhNDM2NmU1MDEiLCJpYXQiOjE3NDQwMDcyOTUsImV4cCI6MTc0NDA5MzY5NX0.82dvsOiszuxPpI55oqAQZsN5gRYSI8uvVrRtcPLyWnaAkZZ6Y6juCzCsr61dC8DcX0adK12of3fc9BnDnSFePg

{
  "title" : "testvocab2",
  "description" : "description2"
}
