DELETE http://127.0.0.1:8080/api/word/1c8e94e2-64e5-4c6c-9329-2860bb4d0e7a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhMWYxMDhjNS1mMjY2LTQxYWEtOTJlNC1iODVhNDM2NmU1MDEiLCJpYXQiOjE3NDQwOTc3MjYsImV4cCI6MTc0NDE4NDEyNn0.RBOafLOE4v8RY0JZ4m3peCpZ_1P0dI4y8IwvsGwDOgSK7ScSM5wm2v6FOrGsaKX7WVeOu36EoTP4doq4VnaYMQ

{
}