POST http://127.0.0.1:8080/api/word/dd5d8d43-61ba-4d7d-8030-7e57cd8be4e8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxNTg1ZjJiNy01MWQ5LTRjZWUtYjJlNi1hMDdmMmZmNmIwMWYiLCJpYXQiOjE3NDY2ODQzMzksImV4cCI6MTc0Njc3MDczOX0.TzEucUGazE9NIWu52oEmXg9VBWxk0HfRYCdkIz471XTNRaECAACB0Azk1f4O0d9yYEUlOtBsaIdVRDKlbtmp8w

{
  "expression" : "aac"
}
